name = "aiken_lang/gift_card"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken_lang/gift_card'"

[repository]
user = "aiken_lang"
project = "gift_card"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"
